# Generated by Django 4.2.16 on 2024-12-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='Catslogan',
            new_name='Catname',
        ),
        migrations.AlterField(
            model_name='cat',
            name='hostname',
            field=models.CharField(default='', max_length=100, verbose_name='Приют'),
        ),
    ]
