# Generated by Django 4.2.16 on 2024-12-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_catslogan_cat_catname_alter_cat_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='Catdescription',
            field=models.CharField(default='', max_length=8000, verbose_name='Описание'),
        ),
    ]
